# **OML Assignment 11**
### B20CS033

In [2]:
pip install gekko

     -------------------------------------- 12.2/12.2 MB 348.3 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
from gekko import GEKKO
from numpy import *

# 1.1

In [4]:
m = GEKKO(remote=False)
c = array([[9],[5],[6],[4]])
A = array([[6,3,5,2],[1,0,0,1],[-1,0,1,0],[0,-1,0,1]])
b = array([[10],[1],[0],[0]])

In [5]:
z = m.Array(m.Var,4,integer=True,lb=0,ub=1)
m.qobj(c,x=z,otype='max')
m.axb(A,b,x=z,etype='<=')
m.options.SOLVER = 1
m.solve()

A
[[ 6.  3.  5.  2.]
 [ 1.  0.  0.  1.]
 [-1.  0.  1.  0.]
 [ 0. -1.  0.  1.]]
b
[[10.  1.  0.  0.]]
 ----------------------------------------------------------------
 APMonitor, Version 1.0.0
 APMonitor Optimization Suite
 ----------------------------------------------------------------
 
 
 --------- APM Model Size ------------
 Each time step contains
   Objects      :  2
   Constants    :  0
   Variables    :  4
   Intermediates:  0
   Connections  :  8
   Equations    :  0
   Residuals    :  0
 
 Number of state variables:    4
 Number of total equations: -  4
 Number of slack variables: -  0
 ---------------------------------------
 Degrees of freedom       :    0
 
 ----------------------------------------------
 Steady State Optimization with APOPT Solver
 ----------------------------------------------
Iter:     1 I:  0 Tm:      0.00 NLPi:    1 Dpth:    0 Lvs:    3 Obj: -1.52E+01 Gap:       NaN
--Integer Solution:  -1.40E+01 Lowest Leaf:  -1.52E+01 Gap:   7.90E-02
Iter:     2 I

In [6]:
print('Objective: ', m.options.OBJFCNVAL)
print(z)

Objective:  -14.0
[[1.0] [1.0] [0.0] [0.0]]


# 1.2

In [7]:
c = array([[7],[3]])
A = array([[5,7],[4,1],[3,-2]])
b = array([[27],[14],[9]])
z1=m.Var(1,integer=True,lb=0,ub=2147483647)
z2=m.Var(1,integer=False,lb=0,ub=2147483647)
z=[z1,z2]
print(z1,z2,z)

int_v5 v6 [1, 1]


In [8]:
m.qobj(c,x=z,otype='max')
m.axb(A,b,x=z,etype='<=')
m.options.SOLVER = 1
m.solve()
print('Objective: ', m.options.OBJFCNVAL)
print(z)

A
[[ 5.  7.]
 [ 4.  1.]
 [ 3. -2.]]
b
[[27. 14.  9.]]
 ----------------------------------------------------------------
 APMonitor, Version 1.0.0
 APMonitor Optimization Suite
 ----------------------------------------------------------------
 
 
 --------- APM Model Size ------------
 Each time step contains
   Objects      :  4
   Constants    :  0
   Variables    :  6
   Intermediates:  0
   Connections  :  12
   Equations    :  0
   Residuals    :  0
 
 Number of state variables:    6
 Number of total equations: -  7
 Number of slack variables: -  0
 ---------------------------------------
 Degrees of freedom       :    -1
 
 * Warning: DOF <= 0
 ----------------------------------------------
 Steady State Optimization with APOPT Solver
 ----------------------------------------------
Iter:     1 I:  0 Tm:     -0.00 NLPi:    3 Dpth:    0 Lvs:    3 Obj: -4.18E+01 Gap:       NaN
--Integer Solution:  -4.01E+01 Lowest Leaf:  -4.18E+01 Gap:   3.96E-02
Iter:     2 I:  0 Tm:      0.00 NLPi:

# 1.3

In [9]:
m = GEKKO(remote=False)
c = array([[-1],[-1]])
A = array([[3,-2],[-8,10]])
b = array([[-1],[10]])

In [10]:
z1=m.Var(1,integer=False,lb=0.3,ub=2147483647)
z2=m.Var(1,integer=True,lb=0,ub=1)
z=[z1,z2]
print(z1,z2,z)


v1 int_v2 [1, 1]


In [11]:
m.qobj(c,x=z,otype='max')
m.axb(A,b,x=z,etype='<=')
m.options.SOLVER = 1
m.solve()
print('Objective: ', m.options.OBJFCNVAL)
print(z)

A
[[ 3. -2.]
 [-8. 10.]]
b
[[-1. 10.]]
 ----------------------------------------------------------------
 APMonitor, Version 1.0.0
 APMonitor Optimization Suite
 ----------------------------------------------------------------
 
 
 --------- APM Model Size ------------
 Each time step contains
   Objects      :  2
   Constants    :  0
   Variables    :  2
   Intermediates:  0
   Connections  :  4
   Equations    :  0
   Residuals    :  0
 
 Number of state variables:    2
 Number of total equations: -  2
 Number of slack variables: -  0
 ---------------------------------------
 Degrees of freedom       :    0
 
 ----------------------------------------------
 Steady State Optimization with APOPT Solver
 ----------------------------------------------
Iter:     1 I:  0 Tm:      0.00 NLPi:    2 Dpth:    0 Lvs:    2 Obj:  1.25E+00 Gap:       NaN
--Integer Solution:   1.30E+00 Lowest Leaf:   1.25E+00 Gap:   3.92E-02
Iter:     2 I:  0 Tm:      0.00 NLPi:    1 Dpth:    1 Lvs:    1 Obj:  1.30E

# 1.4

In [12]:
m = GEKKO(remote=False)
c = array([[120],[85],[105],[140],[70]])
A = array([[55,45,60,50,30],[40,35,25,35,30],[25,20,0,30,0],[0,0,1,1,0]])
b = array([[150],[110],[60],[1]])


In [13]:
z = m.Array(m.Var,5,integer=True,lb=0,ub=1)
m.qobj(c,x=z,otype='max')
m.axb(A,b,x=z,etype='<=')
m.options.SOLVER = 1
m.solve()
print('Objective: ', m.options.OBJFCNVAL)
print(z)

A
[[55. 45. 60. 50. 30.]
 [40. 35. 25. 35. 30.]
 [25. 20.  0. 30.  0.]
 [ 0.  0.  1.  1.  0.]]
b
[[150. 110.  60.   1.]]
 ----------------------------------------------------------------
 APMonitor, Version 1.0.0
 APMonitor Optimization Suite
 ----------------------------------------------------------------
 
 
 --------- APM Model Size ------------
 Each time step contains
   Objects      :  2
   Constants    :  0
   Variables    :  5
   Intermediates:  0
   Connections  :  10
   Equations    :  0
   Residuals    :  0
 
 Number of state variables:    5
 Number of total equations: -  4
 Number of slack variables: -  0
 ---------------------------------------
 Degrees of freedom       :    1
 
 ----------------------------------------------
 Steady State Optimization with APOPT Solver
 ----------------------------------------------
Iter:     1 I:  0 Tm:      0.00 NLPi:    2 Dpth:    0 Lvs:    3 Obj: -3.42E+02 Gap:       NaN
--Integer Solution:  -3.30E+02 Lowest Leaf:  -3.42E+02 Gap:   3